#!/usr/bin/env node

/**
 * just a console tool to run the nake tasks in case you don't have Nake installed locally
 *
 * SEE Nakefile.js for the actual tasks
 *
 * Copyright (C) 2011 Nikolay Nemshilov
 */

require('./Nakefile');
require('./util/lib/nake').start();